apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-adapter-nodejs-dplm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-adapter-nodejs
  template:
    metadata:
      labels:
        app: mqtt-adapter-nodejs
    spec:
      containers:
        - name: mqtt-adapter-nodejs
          image: linhabc/mqtt_adpter_nodejs:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1881
          envFrom:
            - configMapRef:
                name: mqtt-adapter-nodejs-config
