apiVersion: v1
kind: Service
metadata:
  name: mqtt-tttm-svc
  labels:
    app: mqtt-tttm
spec:
  type: NodePort
  ports:
    - port: 1886
      name: mqtt-port
    - port: 8080
      name: htttp-port
  selector:
    app: mqtt-tttm
