apiVersion: v1
kind: Service
metadata:
  name: mqtt-adapter-nodejs-svc
  labels:
    app: mqtt-adapter-nodejs
spec:
  type: NodePort
  ports:
    - port: 1881
      name: mqtt-adapter-nodejs-port
  selector:
    app: mqtt-tttm
